trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.0.x'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'src/**/*.csproj'
    arguments: '-c Dist'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: 'out/bin/**/*.nupkg;!out/bin/**/*.snupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'previews'
    allowPackageConflicts: true
